spring:
  application:
    name: numble
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/numble

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none

logging:
  file:
    path: ./log/numble
    name: numble-log
  pattern:
    console: "%logger{36}.%M \\(%line\\) - %msg%n"
    file: "[%d{HH:mm:ss}] %-3level %logger{5} - %msg %n"
